//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CignaInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int ClaimID { get; set; }
        public string ClaimStatus { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string Description { get; set; }
        public System.DateTime DeclareDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> AmountPaid { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
