//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CignaInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int PlanID { get; set; }
        public int PlanTypeID { get; set; }
        public int CustomerID { get; set; }
        public string PlanDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int PlanFee { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PlanType PlanType { get; set; }
    }
}
